export { default as AdminLayout} from './AdminLayout'
export { default as CreateProduct} from './CreateProduct'
export { default as Dashboard} from './Dashboard'
export { default as ManagerProduct} from './ManagerProduct'
export { default as ManagerUser} from './ManagerUser'